set_property LOC E3 [get_ports {clk_i}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk_i}]
create_clock -add -name sys_clk_pin -period 20.00 [get_ports {clk_i}]

set_property LOC N17 [get_ports {rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst}]

set_property LOC H17 [get_ports {gpio_out[0]}]
set_property LOC K15 [get_ports {gpio_out[1]}]
set_property LOC J13 [get_ports {gpio_out[2]}]
set_property LOC N14 [get_ports {gpio_out[3]}]
set_property LOC R18 [get_ports {gpio_out[4]}]
set_property LOC V17 [get_ports {gpio_out[5]}]
set_property LOC U17 [get_ports {gpio_out[6]}]
set_property LOC U16 [get_ports {gpio_out[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_out[7]}]
