// Generated by rvfi_macros.py

`ifdef YOSYS
`define rvformal_rand_reg rand reg
`define rvformal_rand_const_reg rand const reg
`else
`ifdef SIMULATION
`define rvformal_rand_reg reg
`define rvformal_rand_const_reg reg
`else
`define rvformal_rand_reg wire
`define rvformal_rand_const_reg reg
`endif
`endif

`ifndef RISCV_FORMAL_VALIDADDR
`define RISCV_FORMAL_VALIDADDR(addr) 1
`endif

`ifndef RISCV_FORMAL_IOADDR
`define RISCV_FORMAL_IOADDR(addr) 1
`endif

`define rvformal_addr_valid(a) (`RISCV_FORMAL_VALIDADDR(a))
`define rvformal_addr_io(a) (`rvformal_addr_valid(a) && (`RISCV_FORMAL_IOADDR(a)))
`define rvformal_addr_eq(a, b) ((`rvformal_addr_valid(a) == `rvformal_addr_valid(b)) && (!`rvformal_addr_valid(a) || (a == b)))
`define rvformal_addr_eq_io(a, b) (`rvformal_addr_io(a) ? `rvformal_addr_io(b) : `rvformal_addr_eq(a, b))

`ifdef RISCV_FORMAL_CSR_MVENDORID
`define rvformal_csr_mvendorid_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_wdata;
`define rvformal_csr_mvendorid_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_wdata
`define rvformal_csr_mvendorid_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_wdata
`define rvformal_csr_mvendorid_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_wdata
`define rvformal_csr_mvendorid_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mvendorid_wdata
`define rvformal_csr_mvendorid_conn, \
  .rvfi_csr_mvendorid_rmask (rvfi_csr_mvendorid_rmask), \
  .rvfi_csr_mvendorid_wmask (rvfi_csr_mvendorid_wmask), \
  .rvfi_csr_mvendorid_rdata (rvfi_csr_mvendorid_rdata), \
  .rvfi_csr_mvendorid_wdata (rvfi_csr_mvendorid_wdata)
`define rvformal_csr_mvendorid_channel_conn(_idx), \
  .rvfi_csr_mvendorid_rmask (rvfi_csr_mvendorid_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mvendorid_wmask (rvfi_csr_mvendorid_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mvendorid_rdata (rvfi_csr_mvendorid_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mvendorid_wdata (rvfi_csr_mvendorid_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_mvendorid_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mvendorid_rmask = rvfi_csr_mvendorid_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mvendorid_wmask = rvfi_csr_mvendorid_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mvendorid_rdata = rvfi_csr_mvendorid_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mvendorid_wdata = rvfi_csr_mvendorid_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_mvendorid_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mvendorid_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mvendorid_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mvendorid_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mvendorid_wdata)
`else
`define rvformal_csr_mvendorid_wires
`define rvformal_csr_mvendorid_outputs
`define rvformal_csr_mvendorid_inputs
`define rvformal_csr_mvendorid_conn
`define rvformal_csr_mvendorid_channel(_idx)
`endif
`define rvformal_csr_mvendorid_indices \
localparam [11:0] csr_mindex_mvendorid = 12'hF11; \
localparam [11:0] csr_sindex_mvendorid = 12'hFFF; \
localparam [11:0] csr_uindex_mvendorid = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MARCHID
`define rvformal_csr_marchid_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_wdata;
`define rvformal_csr_marchid_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_wdata
`define rvformal_csr_marchid_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_wdata
`define rvformal_csr_marchid_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_wdata
`define rvformal_csr_marchid_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_marchid_wdata
`define rvformal_csr_marchid_conn, \
  .rvfi_csr_marchid_rmask (rvfi_csr_marchid_rmask), \
  .rvfi_csr_marchid_wmask (rvfi_csr_marchid_wmask), \
  .rvfi_csr_marchid_rdata (rvfi_csr_marchid_rdata), \
  .rvfi_csr_marchid_wdata (rvfi_csr_marchid_wdata)
`define rvformal_csr_marchid_channel_conn(_idx), \
  .rvfi_csr_marchid_rmask (rvfi_csr_marchid_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_marchid_wmask (rvfi_csr_marchid_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_marchid_rdata (rvfi_csr_marchid_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_marchid_wdata (rvfi_csr_marchid_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_marchid_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_marchid_rmask = rvfi_csr_marchid_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_marchid_wmask = rvfi_csr_marchid_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_marchid_rdata = rvfi_csr_marchid_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_marchid_wdata = rvfi_csr_marchid_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_marchid_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_marchid_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_marchid_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_marchid_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_marchid_wdata)
`else
`define rvformal_csr_marchid_wires
`define rvformal_csr_marchid_outputs
`define rvformal_csr_marchid_inputs
`define rvformal_csr_marchid_conn
`define rvformal_csr_marchid_channel(_idx)
`endif
`define rvformal_csr_marchid_indices \
localparam [11:0] csr_mindex_marchid = 12'hF12; \
localparam [11:0] csr_sindex_marchid = 12'hFFF; \
localparam [11:0] csr_uindex_marchid = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MIMPID
`define rvformal_csr_mimpid_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_wdata;
`define rvformal_csr_mimpid_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_wdata
`define rvformal_csr_mimpid_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_wdata
`define rvformal_csr_mimpid_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_wdata
`define rvformal_csr_mimpid_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mimpid_wdata
`define rvformal_csr_mimpid_conn, \
  .rvfi_csr_mimpid_rmask (rvfi_csr_mimpid_rmask), \
  .rvfi_csr_mimpid_wmask (rvfi_csr_mimpid_wmask), \
  .rvfi_csr_mimpid_rdata (rvfi_csr_mimpid_rdata), \
  .rvfi_csr_mimpid_wdata (rvfi_csr_mimpid_wdata)
`define rvformal_csr_mimpid_channel_conn(_idx), \
  .rvfi_csr_mimpid_rmask (rvfi_csr_mimpid_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mimpid_wmask (rvfi_csr_mimpid_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mimpid_rdata (rvfi_csr_mimpid_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mimpid_wdata (rvfi_csr_mimpid_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_mimpid_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mimpid_rmask = rvfi_csr_mimpid_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mimpid_wmask = rvfi_csr_mimpid_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mimpid_rdata = rvfi_csr_mimpid_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mimpid_wdata = rvfi_csr_mimpid_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_mimpid_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mimpid_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mimpid_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mimpid_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mimpid_wdata)
`else
`define rvformal_csr_mimpid_wires
`define rvformal_csr_mimpid_outputs
`define rvformal_csr_mimpid_inputs
`define rvformal_csr_mimpid_conn
`define rvformal_csr_mimpid_channel(_idx)
`endif
`define rvformal_csr_mimpid_indices \
localparam [11:0] csr_mindex_mimpid = 12'hF13; \
localparam [11:0] csr_sindex_mimpid = 12'hFFF; \
localparam [11:0] csr_uindex_mimpid = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MHARTID
`define rvformal_csr_mhartid_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_wdata;
`define rvformal_csr_mhartid_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_wdata
`define rvformal_csr_mhartid_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_wdata
`define rvformal_csr_mhartid_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_wdata
`define rvformal_csr_mhartid_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mhartid_wdata
`define rvformal_csr_mhartid_conn, \
  .rvfi_csr_mhartid_rmask (rvfi_csr_mhartid_rmask), \
  .rvfi_csr_mhartid_wmask (rvfi_csr_mhartid_wmask), \
  .rvfi_csr_mhartid_rdata (rvfi_csr_mhartid_rdata), \
  .rvfi_csr_mhartid_wdata (rvfi_csr_mhartid_wdata)
`define rvformal_csr_mhartid_channel_conn(_idx), \
  .rvfi_csr_mhartid_rmask (rvfi_csr_mhartid_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mhartid_wmask (rvfi_csr_mhartid_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mhartid_rdata (rvfi_csr_mhartid_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mhartid_wdata (rvfi_csr_mhartid_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_mhartid_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mhartid_rmask = rvfi_csr_mhartid_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mhartid_wmask = rvfi_csr_mhartid_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mhartid_rdata = rvfi_csr_mhartid_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mhartid_wdata = rvfi_csr_mhartid_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_mhartid_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mhartid_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mhartid_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mhartid_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mhartid_wdata)
`else
`define rvformal_csr_mhartid_wires
`define rvformal_csr_mhartid_outputs
`define rvformal_csr_mhartid_inputs
`define rvformal_csr_mhartid_conn
`define rvformal_csr_mhartid_channel(_idx)
`endif
`define rvformal_csr_mhartid_indices \
localparam [11:0] csr_mindex_mhartid = 12'hF14; \
localparam [11:0] csr_sindex_mhartid = 12'hFFF; \
localparam [11:0] csr_uindex_mhartid = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MSTATUS
`define rvformal_csr_mstatus_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_wdata;
`define rvformal_csr_mstatus_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_wdata
`define rvformal_csr_mstatus_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_wdata
`define rvformal_csr_mstatus_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_wdata
`define rvformal_csr_mstatus_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatus_wdata
`define rvformal_csr_mstatus_conn, \
  .rvfi_csr_mstatus_rmask (rvfi_csr_mstatus_rmask), \
  .rvfi_csr_mstatus_wmask (rvfi_csr_mstatus_wmask), \
  .rvfi_csr_mstatus_rdata (rvfi_csr_mstatus_rdata), \
  .rvfi_csr_mstatus_wdata (rvfi_csr_mstatus_wdata)
`define rvformal_csr_mstatus_channel_conn(_idx), \
  .rvfi_csr_mstatus_rmask (rvfi_csr_mstatus_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mstatus_wmask (rvfi_csr_mstatus_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mstatus_rdata (rvfi_csr_mstatus_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mstatus_wdata (rvfi_csr_mstatus_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_mstatus_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mstatus_rmask = rvfi_csr_mstatus_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mstatus_wmask = rvfi_csr_mstatus_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mstatus_rdata = rvfi_csr_mstatus_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mstatus_wdata = rvfi_csr_mstatus_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_mstatus_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mstatus_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mstatus_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mstatus_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mstatus_wdata)
`else
`define rvformal_csr_mstatus_wires
`define rvformal_csr_mstatus_outputs
`define rvformal_csr_mstatus_inputs
`define rvformal_csr_mstatus_conn
`define rvformal_csr_mstatus_channel(_idx)
`endif
`define rvformal_csr_mstatus_indices \
localparam [11:0] csr_mindex_mstatus = 12'h300; \
localparam [11:0] csr_sindex_mstatus = 12'hFFF; \
localparam [11:0] csr_uindex_mstatus = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MSTATUSH
`define rvformal_csr_mstatush_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_wdata;
`define rvformal_csr_mstatush_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_wdata
`define rvformal_csr_mstatush_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_wdata
`define rvformal_csr_mstatush_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_wdata
`define rvformal_csr_mstatush_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mstatush_wdata
`define rvformal_csr_mstatush_conn, \
  .rvfi_csr_mstatush_rmask (rvfi_csr_mstatush_rmask), \
  .rvfi_csr_mstatush_wmask (rvfi_csr_mstatush_wmask), \
  .rvfi_csr_mstatush_rdata (rvfi_csr_mstatush_rdata), \
  .rvfi_csr_mstatush_wdata (rvfi_csr_mstatush_wdata)
`define rvformal_csr_mstatush_channel_conn(_idx), \
  .rvfi_csr_mstatush_rmask (rvfi_csr_mstatush_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mstatush_wmask (rvfi_csr_mstatush_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mstatush_rdata (rvfi_csr_mstatush_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mstatush_wdata (rvfi_csr_mstatush_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_mstatush_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mstatush_rmask = rvfi_csr_mstatush_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mstatush_wmask = rvfi_csr_mstatush_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mstatush_rdata = rvfi_csr_mstatush_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mstatush_wdata = rvfi_csr_mstatush_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_mstatush_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mstatush_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mstatush_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mstatush_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mstatush_wdata)
`else
`define rvformal_csr_mstatush_wires
`define rvformal_csr_mstatush_outputs
`define rvformal_csr_mstatush_inputs
`define rvformal_csr_mstatush_conn
`define rvformal_csr_mstatush_channel(_idx)
`endif
`define rvformal_csr_mstatush_indices \
localparam [11:0] csr_mindex_mstatush = 12'h310; \
localparam [11:0] csr_sindex_mstatush = 12'hFFF; \
localparam [11:0] csr_uindex_mstatush = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MISA
`define rvformal_csr_misa_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_wdata;
`define rvformal_csr_misa_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_wdata
`define rvformal_csr_misa_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_wdata
`define rvformal_csr_misa_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_wdata
`define rvformal_csr_misa_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_misa_wdata
`define rvformal_csr_misa_conn, \
  .rvfi_csr_misa_rmask (rvfi_csr_misa_rmask), \
  .rvfi_csr_misa_wmask (rvfi_csr_misa_wmask), \
  .rvfi_csr_misa_rdata (rvfi_csr_misa_rdata), \
  .rvfi_csr_misa_wdata (rvfi_csr_misa_wdata)
`define rvformal_csr_misa_channel_conn(_idx), \
  .rvfi_csr_misa_rmask (rvfi_csr_misa_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_misa_wmask (rvfi_csr_misa_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_misa_rdata (rvfi_csr_misa_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_misa_wdata (rvfi_csr_misa_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_misa_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_misa_rmask = rvfi_csr_misa_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_misa_wmask = rvfi_csr_misa_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_misa_rdata = rvfi_csr_misa_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_misa_wdata = rvfi_csr_misa_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_misa_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_misa_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_misa_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_misa_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_misa_wdata)
`else
`define rvformal_csr_misa_wires
`define rvformal_csr_misa_outputs
`define rvformal_csr_misa_inputs
`define rvformal_csr_misa_conn
`define rvformal_csr_misa_channel(_idx)
`endif
`define rvformal_csr_misa_indices \
localparam [11:0] csr_mindex_misa = 12'h301; \
localparam [11:0] csr_sindex_misa = 12'hFFF; \
localparam [11:0] csr_uindex_misa = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MIE
`define rvformal_csr_mie_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_wdata;
`define rvformal_csr_mie_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_wdata
`define rvformal_csr_mie_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_wdata
`define rvformal_csr_mie_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_wdata
`define rvformal_csr_mie_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mie_wdata
`define rvformal_csr_mie_conn, \
  .rvfi_csr_mie_rmask (rvfi_csr_mie_rmask), \
  .rvfi_csr_mie_wmask (rvfi_csr_mie_wmask), \
  .rvfi_csr_mie_rdata (rvfi_csr_mie_rdata), \
  .rvfi_csr_mie_wdata (rvfi_csr_mie_wdata)
`define rvformal_csr_mie_channel_conn(_idx), \
  .rvfi_csr_mie_rmask (rvfi_csr_mie_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mie_wmask (rvfi_csr_mie_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mie_rdata (rvfi_csr_mie_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mie_wdata (rvfi_csr_mie_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_mie_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mie_rmask = rvfi_csr_mie_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mie_wmask = rvfi_csr_mie_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mie_rdata = rvfi_csr_mie_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mie_wdata = rvfi_csr_mie_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_mie_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mie_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mie_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mie_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mie_wdata)
`else
`define rvformal_csr_mie_wires
`define rvformal_csr_mie_outputs
`define rvformal_csr_mie_inputs
`define rvformal_csr_mie_conn
`define rvformal_csr_mie_channel(_idx)
`endif
`define rvformal_csr_mie_indices \
localparam [11:0] csr_mindex_mie = 12'h304; \
localparam [11:0] csr_sindex_mie = 12'hFFF; \
localparam [11:0] csr_uindex_mie = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MTVEC
`define rvformal_csr_mtvec_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_wdata;
`define rvformal_csr_mtvec_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_wdata
`define rvformal_csr_mtvec_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_wdata
`define rvformal_csr_mtvec_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_wdata
`define rvformal_csr_mtvec_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtvec_wdata
`define rvformal_csr_mtvec_conn, \
  .rvfi_csr_mtvec_rmask (rvfi_csr_mtvec_rmask), \
  .rvfi_csr_mtvec_wmask (rvfi_csr_mtvec_wmask), \
  .rvfi_csr_mtvec_rdata (rvfi_csr_mtvec_rdata), \
  .rvfi_csr_mtvec_wdata (rvfi_csr_mtvec_wdata)
`define rvformal_csr_mtvec_channel_conn(_idx), \
  .rvfi_csr_mtvec_rmask (rvfi_csr_mtvec_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mtvec_wmask (rvfi_csr_mtvec_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mtvec_rdata (rvfi_csr_mtvec_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mtvec_wdata (rvfi_csr_mtvec_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_mtvec_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mtvec_rmask = rvfi_csr_mtvec_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mtvec_wmask = rvfi_csr_mtvec_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mtvec_rdata = rvfi_csr_mtvec_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mtvec_wdata = rvfi_csr_mtvec_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_mtvec_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mtvec_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mtvec_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mtvec_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mtvec_wdata)
`else
`define rvformal_csr_mtvec_wires
`define rvformal_csr_mtvec_outputs
`define rvformal_csr_mtvec_inputs
`define rvformal_csr_mtvec_conn
`define rvformal_csr_mtvec_channel(_idx)
`endif
`define rvformal_csr_mtvec_indices \
localparam [11:0] csr_mindex_mtvec = 12'h305; \
localparam [11:0] csr_sindex_mtvec = 12'hFFF; \
localparam [11:0] csr_uindex_mtvec = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MSCRATCH
`define rvformal_csr_mscratch_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_wdata;
`define rvformal_csr_mscratch_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_wdata
`define rvformal_csr_mscratch_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_wdata
`define rvformal_csr_mscratch_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_wdata
`define rvformal_csr_mscratch_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mscratch_wdata
`define rvformal_csr_mscratch_conn, \
  .rvfi_csr_mscratch_rmask (rvfi_csr_mscratch_rmask), \
  .rvfi_csr_mscratch_wmask (rvfi_csr_mscratch_wmask), \
  .rvfi_csr_mscratch_rdata (rvfi_csr_mscratch_rdata), \
  .rvfi_csr_mscratch_wdata (rvfi_csr_mscratch_wdata)
`define rvformal_csr_mscratch_channel_conn(_idx), \
  .rvfi_csr_mscratch_rmask (rvfi_csr_mscratch_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mscratch_wmask (rvfi_csr_mscratch_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mscratch_rdata (rvfi_csr_mscratch_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mscratch_wdata (rvfi_csr_mscratch_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_mscratch_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mscratch_rmask = rvfi_csr_mscratch_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mscratch_wmask = rvfi_csr_mscratch_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mscratch_rdata = rvfi_csr_mscratch_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mscratch_wdata = rvfi_csr_mscratch_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_mscratch_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mscratch_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mscratch_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mscratch_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mscratch_wdata)
`else
`define rvformal_csr_mscratch_wires
`define rvformal_csr_mscratch_outputs
`define rvformal_csr_mscratch_inputs
`define rvformal_csr_mscratch_conn
`define rvformal_csr_mscratch_channel(_idx)
`endif
`define rvformal_csr_mscratch_indices \
localparam [11:0] csr_mindex_mscratch = 12'h340; \
localparam [11:0] csr_sindex_mscratch = 12'hFFF; \
localparam [11:0] csr_uindex_mscratch = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MEPC
`define rvformal_csr_mepc_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_wdata;
`define rvformal_csr_mepc_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_wdata
`define rvformal_csr_mepc_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_wdata
`define rvformal_csr_mepc_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_wdata
`define rvformal_csr_mepc_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mepc_wdata
`define rvformal_csr_mepc_conn, \
  .rvfi_csr_mepc_rmask (rvfi_csr_mepc_rmask), \
  .rvfi_csr_mepc_wmask (rvfi_csr_mepc_wmask), \
  .rvfi_csr_mepc_rdata (rvfi_csr_mepc_rdata), \
  .rvfi_csr_mepc_wdata (rvfi_csr_mepc_wdata)
`define rvformal_csr_mepc_channel_conn(_idx), \
  .rvfi_csr_mepc_rmask (rvfi_csr_mepc_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mepc_wmask (rvfi_csr_mepc_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mepc_rdata (rvfi_csr_mepc_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mepc_wdata (rvfi_csr_mepc_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_mepc_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mepc_rmask = rvfi_csr_mepc_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mepc_wmask = rvfi_csr_mepc_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mepc_rdata = rvfi_csr_mepc_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mepc_wdata = rvfi_csr_mepc_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_mepc_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mepc_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mepc_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mepc_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mepc_wdata)
`else
`define rvformal_csr_mepc_wires
`define rvformal_csr_mepc_outputs
`define rvformal_csr_mepc_inputs
`define rvformal_csr_mepc_conn
`define rvformal_csr_mepc_channel(_idx)
`endif
`define rvformal_csr_mepc_indices \
localparam [11:0] csr_mindex_mepc = 12'h341; \
localparam [11:0] csr_sindex_mepc = 12'hFFF; \
localparam [11:0] csr_uindex_mepc = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MCAUSE
`define rvformal_csr_mcause_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_wdata;
`define rvformal_csr_mcause_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_wdata
`define rvformal_csr_mcause_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_wdata
`define rvformal_csr_mcause_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_wdata
`define rvformal_csr_mcause_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mcause_wdata
`define rvformal_csr_mcause_conn, \
  .rvfi_csr_mcause_rmask (rvfi_csr_mcause_rmask), \
  .rvfi_csr_mcause_wmask (rvfi_csr_mcause_wmask), \
  .rvfi_csr_mcause_rdata (rvfi_csr_mcause_rdata), \
  .rvfi_csr_mcause_wdata (rvfi_csr_mcause_wdata)
`define rvformal_csr_mcause_channel_conn(_idx), \
  .rvfi_csr_mcause_rmask (rvfi_csr_mcause_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mcause_wmask (rvfi_csr_mcause_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mcause_rdata (rvfi_csr_mcause_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mcause_wdata (rvfi_csr_mcause_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_mcause_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mcause_rmask = rvfi_csr_mcause_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mcause_wmask = rvfi_csr_mcause_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mcause_rdata = rvfi_csr_mcause_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mcause_wdata = rvfi_csr_mcause_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_mcause_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mcause_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mcause_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mcause_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mcause_wdata)
`else
`define rvformal_csr_mcause_wires
`define rvformal_csr_mcause_outputs
`define rvformal_csr_mcause_inputs
`define rvformal_csr_mcause_conn
`define rvformal_csr_mcause_channel(_idx)
`endif
`define rvformal_csr_mcause_indices \
localparam [11:0] csr_mindex_mcause = 12'h342; \
localparam [11:0] csr_sindex_mcause = 12'hFFF; \
localparam [11:0] csr_uindex_mcause = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MTVAL
`define rvformal_csr_mtval_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_wdata;
`define rvformal_csr_mtval_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_wdata
`define rvformal_csr_mtval_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_wdata
`define rvformal_csr_mtval_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_wdata
`define rvformal_csr_mtval_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mtval_wdata
`define rvformal_csr_mtval_conn, \
  .rvfi_csr_mtval_rmask (rvfi_csr_mtval_rmask), \
  .rvfi_csr_mtval_wmask (rvfi_csr_mtval_wmask), \
  .rvfi_csr_mtval_rdata (rvfi_csr_mtval_rdata), \
  .rvfi_csr_mtval_wdata (rvfi_csr_mtval_wdata)
`define rvformal_csr_mtval_channel_conn(_idx), \
  .rvfi_csr_mtval_rmask (rvfi_csr_mtval_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mtval_wmask (rvfi_csr_mtval_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mtval_rdata (rvfi_csr_mtval_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mtval_wdata (rvfi_csr_mtval_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_mtval_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mtval_rmask = rvfi_csr_mtval_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mtval_wmask = rvfi_csr_mtval_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mtval_rdata = rvfi_csr_mtval_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mtval_wdata = rvfi_csr_mtval_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_mtval_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mtval_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mtval_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mtval_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mtval_wdata)
`else
`define rvformal_csr_mtval_wires
`define rvformal_csr_mtval_outputs
`define rvformal_csr_mtval_inputs
`define rvformal_csr_mtval_conn
`define rvformal_csr_mtval_channel(_idx)
`endif
`define rvformal_csr_mtval_indices \
localparam [11:0] csr_mindex_mtval = 12'h343; \
localparam [11:0] csr_sindex_mtval = 12'hFFF; \
localparam [11:0] csr_uindex_mtval = 12'hFFF; \

`ifdef RISCV_FORMAL_CSR_MIP
`define rvformal_csr_mip_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_wdata;
`define rvformal_csr_mip_outputs, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_wdata
`define rvformal_csr_mip_channel_outputs, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_rmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_wmask, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_rdata, \
  output [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_wdata
`define rvformal_csr_mip_inputs, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_wdata
`define rvformal_csr_mip_channel_inputs, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_rmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_wmask, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_rdata, \
  input [`RISCV_FORMAL_XLEN - 1 : 0] rvfi_csr_mip_wdata
`define rvformal_csr_mip_conn, \
  .rvfi_csr_mip_rmask (rvfi_csr_mip_rmask), \
  .rvfi_csr_mip_wmask (rvfi_csr_mip_wmask), \
  .rvfi_csr_mip_rdata (rvfi_csr_mip_rdata), \
  .rvfi_csr_mip_wdata (rvfi_csr_mip_wdata)
`define rvformal_csr_mip_channel_conn(_idx), \
  .rvfi_csr_mip_rmask (rvfi_csr_mip_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mip_wmask (rvfi_csr_mip_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mip_rdata (rvfi_csr_mip_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]), \
  .rvfi_csr_mip_wdata (rvfi_csr_mip_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN])
`define rvformal_csr_mip_channel(_idx) \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mip_rmask = rvfi_csr_mip_rmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mip_wmask = rvfi_csr_mip_wmask [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mip_rdata = rvfi_csr_mip_rdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN]; \
  wire [`RISCV_FORMAL_XLEN - 1 : 0] csr_mip_wdata = rvfi_csr_mip_wdata [(_idx)*(`RISCV_FORMAL_XLEN) +: `RISCV_FORMAL_XLEN];
`define rvformal_csr_mip_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mip_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mip_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mip_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN, csr_mip_wdata)
`else
`define rvformal_csr_mip_wires
`define rvformal_csr_mip_outputs
`define rvformal_csr_mip_inputs
`define rvformal_csr_mip_conn
`define rvformal_csr_mip_channel(_idx)
`endif
`define rvformal_csr_mip_indices \
localparam [11:0] csr_mindex_mip = 12'h344; \
localparam [11:0] csr_sindex_mip = 12'hFFF; \
localparam [11:0] csr_uindex_mip = 12'hFFF; \

`define RVFI_INDICES \
`rvformal_csr_mvendorid_indices \
`rvformal_csr_marchid_indices \
`rvformal_csr_mimpid_indices \
`rvformal_csr_mhartid_indices \
`rvformal_csr_mstatus_indices \
`rvformal_csr_mstatush_indices \
`rvformal_csr_misa_indices \
`rvformal_csr_mie_indices \
`rvformal_csr_mtvec_indices \
`rvformal_csr_mscratch_indices \
`rvformal_csr_mepc_indices \
`rvformal_csr_mcause_indices \
`rvformal_csr_mtval_indices \
`rvformal_csr_mip_indices \
`rvformal_custom_csr_indices

`ifdef RISCV_FORMAL_CUSTOM_CSR_INPUTS
`define rvformal_custom_csr_inputs `RISCV_FORMAL_CUSTOM_CSR_INPUTS
`else
`define rvformal_custom_csr_inputs
`endif
`ifdef RISCV_FORMAL_CUSTOM_CSR_WIRES
`define rvformal_custom_csr_wires `RISCV_FORMAL_CUSTOM_CSR_WIRES
`else
`define rvformal_custom_csr_wires
`endif
`ifdef RISCV_FORMAL_CUSTOM_CSR_CONN
`define rvformal_custom_csr_conn `RISCV_FORMAL_CUSTOM_CSR_CONN
`else
`define rvformal_custom_csr_conn
`endif
`ifdef RISCV_FORMAL_CUSTOM_CSR_CHANNEL
`define rvformal_custom_csr_channel(_idx) `RISCV_FORMAL_CUSTOM_CSR_CHANNEL(_idx)
`else
`define rvformal_custom_csr_channel(_idx)
`endif
`ifdef RISCV_FORMAL_CUSTOM_CSR_SIGNALS
`define rvformal_custom_csr_signals `RISCV_FORMAL_CUSTOM_CSR_SIGNALS
`else
`define rvformal_custom_csr_signals
`endif
`ifdef RISCV_FORMAL_CUSTOM_CSR_OUTPUTS
`define rvformal_custom_csr_outputs `RISCV_FORMAL_CUSTOM_CSR_OUTPUTS
`else
`define rvformal_custom_csr_outputs
`endif
`ifdef RISCV_FORMAL_CUSTOM_CSR_INDICES
`define rvformal_custom_csr_indices `RISCV_FORMAL_CUSTOM_CSR_INDICES
`else
`define rvformal_custom_csr_indices
`endif
`ifdef RISCV_FORMAL_MEM_FAULT
`define rvformal_mem_fault_wires \
  (* keep *) wire [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_mem_fault      ; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_fault_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_fault_wmask;
`define rvformal_mem_fault_outputs, \
  output [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_mem_fault      , \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_fault_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_fault_wmask
`define rvformal_mem_fault_channel_outputs, \
  output [                       0 : 0] rvfi_mem_fault      , \
  output [`RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_fault_rmask, \
  output [`RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_fault_wmask
`define rvformal_mem_fault_inputs, \
  input [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_mem_fault      , \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_fault_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_fault_wmask
`define rvformal_mem_fault_channel_inputs, \
  input [                       0 : 0] rvfi_mem_fault      , \
  input [`RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_fault_rmask, \
  input [`RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_fault_wmask
`define rvformal_mem_fault_conn, \
  .rvfi_mem_fault       (rvfi_mem_fault      ), \
  .rvfi_mem_fault_rmask (rvfi_mem_fault_rmask), \
  .rvfi_mem_fault_wmask (rvfi_mem_fault_wmask)
`define rvformal_mem_fault_channel_conn(_idx), \
  .rvfi_mem_fault       (rvfi_mem_fault       [ _idx                         +:                  1  ]), \
  .rvfi_mem_fault_rmask (rvfi_mem_fault_rmask [(_idx)*(`RISCV_FORMAL_XLEN/8) +: `RISCV_FORMAL_XLEN/8]), \
  .rvfi_mem_fault_wmask (rvfi_mem_fault_wmask [(_idx)*(`RISCV_FORMAL_XLEN/8) +: `RISCV_FORMAL_XLEN/8])
`define rvformal_mem_fault_channel(_idx) \
  wire [                       0 : 0] mem_fault       = rvfi_mem_fault       [ _idx                         +:                  1  ]; \
  wire [`RISCV_FORMAL_XLEN/8 - 1 : 0] mem_fault_rmask = rvfi_mem_fault_rmask [(_idx)*(`RISCV_FORMAL_XLEN/8) +: `RISCV_FORMAL_XLEN/8]; \
  wire [`RISCV_FORMAL_XLEN/8 - 1 : 0] mem_fault_wmask = rvfi_mem_fault_wmask [(_idx)*(`RISCV_FORMAL_XLEN/8) +: `RISCV_FORMAL_XLEN/8];
`define rvformal_mem_fault_signals \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET,                  1  , mem_fault      ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN/8, mem_fault_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN/8, mem_fault_wmask)
`else
`define rvformal_mem_fault_wires
`define rvformal_mem_fault_outputs
`define rvformal_mem_fault_inputs
`define rvformal_mem_fault_conn
`define rvformal_mem_fault_channel(_idx)
`endif
`define RVFI_WIRES \
  (* keep *) wire [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_valid    ; \
  (* keep *) wire [`RISCV_FORMAL_NRET *                 64   - 1 : 0] rvfi_order    ; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_ILEN   - 1 : 0] rvfi_insn     ; \
  (* keep *) wire [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_trap     ; \
  (* keep *) wire [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_halt     ; \
  (* keep *) wire [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_intr     ; \
  (* keep *) wire [`RISCV_FORMAL_NRET *                  2   - 1 : 0] rvfi_mode     ; \
  (* keep *) wire [`RISCV_FORMAL_NRET *                  2   - 1 : 0] rvfi_ixl      ; \
  (* keep *) wire [`RISCV_FORMAL_NRET *                  5   - 1 : 0] rvfi_rs1_addr ; \
  (* keep *) wire [`RISCV_FORMAL_NRET *                  5   - 1 : 0] rvfi_rs2_addr ; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rs1_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rs2_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET *                  5   - 1 : 0] rvfi_rd_addr  ; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rd_wdata ; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_pc_rdata ; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_pc_wdata ; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_addr ; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_wdata; \
  `rvformal_mem_fault_wires \
  `rvformal_csr_mvendorid_wires \
  `rvformal_csr_marchid_wires \
  `rvformal_csr_mimpid_wires \
  `rvformal_csr_mhartid_wires \
  `rvformal_csr_mstatus_wires \
  `rvformal_csr_mstatush_wires \
  `rvformal_csr_misa_wires \
  `rvformal_csr_mie_wires \
  `rvformal_csr_mtvec_wires \
  `rvformal_csr_mscratch_wires \
  `rvformal_csr_mepc_wires \
  `rvformal_csr_mcause_wires \
  `rvformal_csr_mtval_wires \
  `rvformal_csr_mip_wires \
  `rvformal_custom_csr_wires
`define RVFI_OUTPUTS \
  output [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_valid    , \
  output [`RISCV_FORMAL_NRET *                 64   - 1 : 0] rvfi_order    , \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_ILEN   - 1 : 0] rvfi_insn     , \
  output [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_trap     , \
  output [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_halt     , \
  output [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_intr     , \
  output [`RISCV_FORMAL_NRET *                  2   - 1 : 0] rvfi_mode     , \
  output [`RISCV_FORMAL_NRET *                  2   - 1 : 0] rvfi_ixl      , \
  output [`RISCV_FORMAL_NRET *                  5   - 1 : 0] rvfi_rs1_addr , \
  output [`RISCV_FORMAL_NRET *                  5   - 1 : 0] rvfi_rs2_addr , \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rs1_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rs2_rdata, \
  output [`RISCV_FORMAL_NRET *                  5   - 1 : 0] rvfi_rd_addr  , \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rd_wdata , \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_pc_rdata , \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_pc_wdata , \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_addr , \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_rmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_wmask, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_rdata, \
  output [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_wdata \
  `rvformal_mem_fault_outputs \
  `rvformal_csr_mvendorid_outputs \
  `rvformal_csr_marchid_outputs \
  `rvformal_csr_mimpid_outputs \
  `rvformal_csr_mhartid_outputs \
  `rvformal_csr_mstatus_outputs \
  `rvformal_csr_mstatush_outputs \
  `rvformal_csr_misa_outputs \
  `rvformal_csr_mie_outputs \
  `rvformal_csr_mtvec_outputs \
  `rvformal_csr_mscratch_outputs \
  `rvformal_csr_mepc_outputs \
  `rvformal_csr_mcause_outputs \
  `rvformal_csr_mtval_outputs \
  `rvformal_csr_mip_outputs \
  `rvformal_custom_csr_outputs
`define RVFI_CHANNEL_OUTPUTS \
  output [                       0 : 0] rvfi_valid    , \
  output [                64   - 1 : 0] rvfi_order    , \
  output [`RISCV_FORMAL_ILEN   - 1 : 0] rvfi_insn     , \
  output [                       0 : 0] rvfi_trap     , \
  output [                       0 : 0] rvfi_halt     , \
  output [                       0 : 0] rvfi_intr     , \
  output [                 2   - 1 : 0] rvfi_mode     , \
  output [                 2   - 1 : 0] rvfi_ixl      , \
  output [                 5   - 1 : 0] rvfi_rs1_addr , \
  output [                 5   - 1 : 0] rvfi_rs2_addr , \
  output [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rs1_rdata, \
  output [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rs2_rdata, \
  output [                 5   - 1 : 0] rvfi_rd_addr  , \
  output [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rd_wdata , \
  output [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_pc_rdata , \
  output [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_pc_wdata , \
  output [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_addr , \
  output [`RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_rmask, \
  output [`RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_wmask, \
  output [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_rdata, \
  output [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_wdata \
  `rvformal_mem_fault_channel_outputs \
  `rvformal_csr_mvendorid_channel_outputs \
  `rvformal_csr_marchid_channel_outputs \
  `rvformal_csr_mimpid_channel_outputs \
  `rvformal_csr_mhartid_channel_outputs \
  `rvformal_csr_mstatus_channel_outputs \
  `rvformal_csr_mstatush_channel_outputs \
  `rvformal_csr_misa_channel_outputs \
  `rvformal_csr_mie_channel_outputs \
  `rvformal_csr_mtvec_channel_outputs \
  `rvformal_csr_mscratch_channel_outputs \
  `rvformal_csr_mepc_channel_outputs \
  `rvformal_csr_mcause_channel_outputs \
  `rvformal_csr_mtval_channel_outputs \
  `rvformal_csr_mip_channel_outputs \
  `rvformal_custom_csr_channel_outputs
`define RVFI_INPUTS \
  input [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_valid    , \
  input [`RISCV_FORMAL_NRET *                 64   - 1 : 0] rvfi_order    , \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_ILEN   - 1 : 0] rvfi_insn     , \
  input [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_trap     , \
  input [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_halt     , \
  input [`RISCV_FORMAL_NRET                        - 1 : 0] rvfi_intr     , \
  input [`RISCV_FORMAL_NRET *                  2   - 1 : 0] rvfi_mode     , \
  input [`RISCV_FORMAL_NRET *                  2   - 1 : 0] rvfi_ixl      , \
  input [`RISCV_FORMAL_NRET *                  5   - 1 : 0] rvfi_rs1_addr , \
  input [`RISCV_FORMAL_NRET *                  5   - 1 : 0] rvfi_rs2_addr , \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rs1_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rs2_rdata, \
  input [`RISCV_FORMAL_NRET *                  5   - 1 : 0] rvfi_rd_addr  , \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rd_wdata , \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_pc_rdata , \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_pc_wdata , \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_addr , \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_rmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_wmask, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_rdata, \
  input [`RISCV_FORMAL_NRET * `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_wdata \
  `rvformal_mem_fault_inputs \
  `rvformal_csr_mvendorid_inputs \
  `rvformal_csr_marchid_inputs \
  `rvformal_csr_mimpid_inputs \
  `rvformal_csr_mhartid_inputs \
  `rvformal_csr_mstatus_inputs \
  `rvformal_csr_mstatush_inputs \
  `rvformal_csr_misa_inputs \
  `rvformal_csr_mie_inputs \
  `rvformal_csr_mtvec_inputs \
  `rvformal_csr_mscratch_inputs \
  `rvformal_csr_mepc_inputs \
  `rvformal_csr_mcause_inputs \
  `rvformal_csr_mtval_inputs \
  `rvformal_csr_mip_inputs \
  `rvformal_custom_csr_inputs
`define RVFI_CHANNEL_INPUTS \
  input [                       0 : 0] rvfi_valid    , \
  input [                64   - 1 : 0] rvfi_order    , \
  input [`RISCV_FORMAL_ILEN   - 1 : 0] rvfi_insn     , \
  input [                       0 : 0] rvfi_trap     , \
  input [                       0 : 0] rvfi_halt     , \
  input [                       0 : 0] rvfi_intr     , \
  input [                 2   - 1 : 0] rvfi_mode     , \
  input [                 2   - 1 : 0] rvfi_ixl      , \
  input [                 5   - 1 : 0] rvfi_rs1_addr , \
  input [                 5   - 1 : 0] rvfi_rs2_addr , \
  input [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rs1_rdata, \
  input [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rs2_rdata, \
  input [                 5   - 1 : 0] rvfi_rd_addr  , \
  input [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rd_wdata , \
  input [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_pc_rdata , \
  input [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_pc_wdata , \
  input [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_addr , \
  input [`RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_rmask, \
  input [`RISCV_FORMAL_XLEN/8 - 1 : 0] rvfi_mem_wmask, \
  input [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_rdata, \
  input [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_wdata \
  `rvformal_mem_fault_channel_inputs \
  `rvformal_csr_mvendorid_channel_inputs \
  `rvformal_csr_marchid_channel_inputs \
  `rvformal_csr_mimpid_channel_inputs \
  `rvformal_csr_mhartid_channel_inputs \
  `rvformal_csr_mstatus_channel_inputs \
  `rvformal_csr_mstatush_channel_inputs \
  `rvformal_csr_misa_channel_inputs \
  `rvformal_csr_mie_channel_inputs \
  `rvformal_csr_mtvec_channel_inputs \
  `rvformal_csr_mscratch_channel_inputs \
  `rvformal_csr_mepc_channel_inputs \
  `rvformal_csr_mcause_channel_inputs \
  `rvformal_csr_mtval_channel_inputs \
  `rvformal_csr_mip_channel_inputs \
  `rvformal_custom_csr_channel_inputs
`define RVFI_CONN \
  .rvfi_valid     (rvfi_valid    ), \
  .rvfi_order     (rvfi_order    ), \
  .rvfi_insn      (rvfi_insn     ), \
  .rvfi_trap      (rvfi_trap     ), \
  .rvfi_halt      (rvfi_halt     ), \
  .rvfi_intr      (rvfi_intr     ), \
  .rvfi_mode      (rvfi_mode     ), \
  .rvfi_ixl       (rvfi_ixl      ), \
  .rvfi_rs1_addr  (rvfi_rs1_addr ), \
  .rvfi_rs2_addr  (rvfi_rs2_addr ), \
  .rvfi_rs1_rdata (rvfi_rs1_rdata), \
  .rvfi_rs2_rdata (rvfi_rs2_rdata), \
  .rvfi_rd_addr   (rvfi_rd_addr  ), \
  .rvfi_rd_wdata  (rvfi_rd_wdata ), \
  .rvfi_pc_rdata  (rvfi_pc_rdata ), \
  .rvfi_pc_wdata  (rvfi_pc_wdata ), \
  .rvfi_mem_addr  (rvfi_mem_addr ), \
  .rvfi_mem_rmask (rvfi_mem_rmask), \
  .rvfi_mem_wmask (rvfi_mem_wmask), \
  .rvfi_mem_rdata (rvfi_mem_rdata), \
  .rvfi_mem_wdata (rvfi_mem_wdata) \
  `rvformal_mem_fault_conn \
  `rvformal_csr_mvendorid_conn \
  `rvformal_csr_marchid_conn \
  `rvformal_csr_mimpid_conn \
  `rvformal_csr_mhartid_conn \
  `rvformal_csr_mstatus_conn \
  `rvformal_csr_mstatush_conn \
  `rvformal_csr_misa_conn \
  `rvformal_csr_mie_conn \
  `rvformal_csr_mtvec_conn \
  `rvformal_csr_mscratch_conn \
  `rvformal_csr_mepc_conn \
  `rvformal_csr_mcause_conn \
  `rvformal_csr_mtval_conn \
  `rvformal_csr_mip_conn \
  `rvformal_custom_csr_conn
`define RVFI_CHANNEL_CONN(_idx) \
  .rvfi_valid     (rvfi_valid     [ _idx                         +:                  1  ]), \
  .rvfi_order     (rvfi_order     [(_idx)*(                64  ) +:                 64  ]), \
  .rvfi_insn      (rvfi_insn      [(_idx)*(`RISCV_FORMAL_ILEN  ) +: `RISCV_FORMAL_ILEN  ]), \
  .rvfi_trap      (rvfi_trap      [ _idx                         +:                  1  ]), \
  .rvfi_halt      (rvfi_halt      [ _idx                         +:                  1  ]), \
  .rvfi_intr      (rvfi_intr      [ _idx                         +:                  1  ]), \
  .rvfi_mode      (rvfi_mode      [(_idx)*(                 2  ) +:                  2  ]), \
  .rvfi_ixl       (rvfi_ixl       [(_idx)*(                 2  ) +:                  2  ]), \
  .rvfi_rs1_addr  (rvfi_rs1_addr  [(_idx)*(                 5  ) +:                  5  ]), \
  .rvfi_rs2_addr  (rvfi_rs2_addr  [(_idx)*(                 5  ) +:                  5  ]), \
  .rvfi_rs1_rdata (rvfi_rs1_rdata [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]), \
  .rvfi_rs2_rdata (rvfi_rs2_rdata [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]), \
  .rvfi_rd_addr   (rvfi_rd_addr   [(_idx)*(                 5  ) +:                  5  ]), \
  .rvfi_rd_wdata  (rvfi_rd_wdata  [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]), \
  .rvfi_pc_rdata  (rvfi_pc_rdata  [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]), \
  .rvfi_pc_wdata  (rvfi_pc_wdata  [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]), \
  .rvfi_mem_addr  (rvfi_mem_addr  [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]), \
  .rvfi_mem_rmask (rvfi_mem_rmask [(_idx)*(`RISCV_FORMAL_XLEN/8) +: `RISCV_FORMAL_XLEN/8]), \
  .rvfi_mem_wmask (rvfi_mem_wmask [(_idx)*(`RISCV_FORMAL_XLEN/8) +: `RISCV_FORMAL_XLEN/8]), \
  .rvfi_mem_rdata (rvfi_mem_rdata [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]), \
  .rvfi_mem_wdata (rvfi_mem_wdata [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]) \
  `rvformal_mem_fault_channel_conn(_idx) \
  `rvformal_csr_mvendorid_channel_conn(_idx) \
  `rvformal_csr_marchid_channel_conn(_idx) \
  `rvformal_csr_mimpid_channel_conn(_idx) \
  `rvformal_csr_mhartid_channel_conn(_idx) \
  `rvformal_csr_mstatus_channel_conn(_idx) \
  `rvformal_csr_mstatush_channel_conn(_idx) \
  `rvformal_csr_misa_channel_conn(_idx) \
  `rvformal_csr_mie_channel_conn(_idx) \
  `rvformal_csr_mtvec_channel_conn(_idx) \
  `rvformal_csr_mscratch_channel_conn(_idx) \
  `rvformal_csr_mepc_channel_conn(_idx) \
  `rvformal_csr_mcause_channel_conn(_idx) \
  `rvformal_csr_mtval_channel_conn(_idx) \
  `rvformal_csr_mip_channel_conn(_idx) \
  `rvformal_custom_csr_channel_conn(_idx)
`define RVFI_GETCHANNEL(_idx) \
  wire [                       0 : 0] valid     = rvfi_valid     [ _idx                         +:                  1  ]; \
  wire [                64   - 1 : 0] order     = rvfi_order     [(_idx)*(                64  ) +:                 64  ]; \
  wire [`RISCV_FORMAL_ILEN   - 1 : 0] insn      = rvfi_insn      [(_idx)*(`RISCV_FORMAL_ILEN  ) +: `RISCV_FORMAL_ILEN  ]; \
  wire [                       0 : 0] trap      = rvfi_trap      [ _idx                         +:                  1  ]; \
  wire [                       0 : 0] halt      = rvfi_halt      [ _idx                         +:                  1  ]; \
  wire [                       0 : 0] intr      = rvfi_intr      [ _idx                         +:                  1  ]; \
  wire [                 2   - 1 : 0] mode      = rvfi_mode      [(_idx)*(                 2  ) +:                  2  ]; \
  wire [                 2   - 1 : 0] ixl       = rvfi_ixl       [(_idx)*(                 2  ) +:                  2  ]; \
  wire [                 5   - 1 : 0] rs1_addr  = rvfi_rs1_addr  [(_idx)*(                 5  ) +:                  5  ]; \
  wire [                 5   - 1 : 0] rs2_addr  = rvfi_rs2_addr  [(_idx)*(                 5  ) +:                  5  ]; \
  wire [`RISCV_FORMAL_XLEN   - 1 : 0] rs1_rdata = rvfi_rs1_rdata [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]; \
  wire [`RISCV_FORMAL_XLEN   - 1 : 0] rs2_rdata = rvfi_rs2_rdata [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]; \
  wire [                 5   - 1 : 0] rd_addr   = rvfi_rd_addr   [(_idx)*(                 5  ) +:                  5  ]; \
  wire [`RISCV_FORMAL_XLEN   - 1 : 0] rd_wdata  = rvfi_rd_wdata  [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]; \
  wire [`RISCV_FORMAL_XLEN   - 1 : 0] pc_rdata  = rvfi_pc_rdata  [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]; \
  wire [`RISCV_FORMAL_XLEN   - 1 : 0] pc_wdata  = rvfi_pc_wdata  [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]; \
  wire [`RISCV_FORMAL_XLEN   - 1 : 0] mem_addr  = rvfi_mem_addr  [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]; \
  wire [`RISCV_FORMAL_XLEN/8 - 1 : 0] mem_rmask = rvfi_mem_rmask [(_idx)*(`RISCV_FORMAL_XLEN/8) +: `RISCV_FORMAL_XLEN/8]; \
  wire [`RISCV_FORMAL_XLEN/8 - 1 : 0] mem_wmask = rvfi_mem_wmask [(_idx)*(`RISCV_FORMAL_XLEN/8) +: `RISCV_FORMAL_XLEN/8]; \
  wire [`RISCV_FORMAL_XLEN   - 1 : 0] mem_rdata = rvfi_mem_rdata [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]; \
  wire [`RISCV_FORMAL_XLEN   - 1 : 0] mem_wdata = rvfi_mem_wdata [(_idx)*(`RISCV_FORMAL_XLEN  ) +: `RISCV_FORMAL_XLEN  ]; \
  `rvformal_mem_fault_channel(_idx) \
  `rvformal_csr_mvendorid_channel(_idx) \
  `rvformal_csr_marchid_channel(_idx) \
  `rvformal_csr_mimpid_channel(_idx) \
  `rvformal_csr_mhartid_channel(_idx) \
  `rvformal_csr_mstatus_channel(_idx) \
  `rvformal_csr_mstatush_channel(_idx) \
  `rvformal_csr_misa_channel(_idx) \
  `rvformal_csr_mie_channel(_idx) \
  `rvformal_csr_mtvec_channel(_idx) \
  `rvformal_csr_mscratch_channel(_idx) \
  `rvformal_csr_mepc_channel(_idx) \
  `rvformal_csr_mcause_channel(_idx) \
  `rvformal_csr_mtval_channel(_idx) \
  `rvformal_csr_mip_channel(_idx) \
  `rvformal_custom_csr_channel(_idx)
`define RVFI_SIGNALS \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET,                  1  , valid    ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET,                 64  , order    ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_ILEN  , insn     ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET,                  1  , trap     ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET,                  1  , halt     ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET,                  1  , intr     ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET,                  2  , mode     ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET,                  2  , ixl      ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET,                  5  , rs1_addr ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET,                  5  , rs2_addr ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN  , rs1_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN  , rs2_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET,                  5  , rd_addr  ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN  , rd_wdata ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN  , pc_rdata ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN  , pc_wdata ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN  , mem_addr ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN/8, mem_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN/8, mem_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN  , mem_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NRET, `RISCV_FORMAL_XLEN  , mem_wdata) \
  `rvformal_mem_fault_signals \
  `rvformal_csr_mvendorid_signals \
  `rvformal_csr_marchid_signals \
  `rvformal_csr_mimpid_signals \
  `rvformal_csr_mhartid_signals \
  `rvformal_csr_mstatus_signals \
  `rvformal_csr_mstatush_signals \
  `rvformal_csr_misa_signals \
  `rvformal_csr_mie_signals \
  `rvformal_csr_mtvec_signals \
  `rvformal_csr_mscratch_signals \
  `rvformal_csr_mepc_signals \
  `rvformal_csr_mcause_signals \
  `rvformal_csr_mtval_signals \
  `rvformal_csr_mip_signals \
  `rvformal_custom_csr_signals

`define RVFI_CHANNEL(_name, _idx) \
generate if(1) begin:_name \
  `RVFI_GETCHANNEL(_idx) \
end endgenerate
`ifdef RISCV_FORMAL_BUS
`define RVFI_BUS_WIRES \
  (* keep *) wire [`RISCV_FORMAL_NBUS                          - 1 : 0] rvfi_bus_valid; \
  (* keep *) wire [`RISCV_FORMAL_NBUS                          - 1 : 0] rvfi_bus_insn ; \
  (* keep *) wire [`RISCV_FORMAL_NBUS                          - 1 : 0] rvfi_bus_data ; \
  (* keep *) wire [`RISCV_FORMAL_NBUS                          - 1 : 0] rvfi_bus_fault; \
  (* keep *) wire [`RISCV_FORMAL_NBUS *   `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_bus_addr ; \
  (* keep *) wire [`RISCV_FORMAL_NBUS * `RISCV_FORMAL_BUSLEN/8 - 1 : 0] rvfi_bus_rmask; \
  (* keep *) wire [`RISCV_FORMAL_NBUS * `RISCV_FORMAL_BUSLEN/8 - 1 : 0] rvfi_bus_wmask; \
  (* keep *) wire [`RISCV_FORMAL_NBUS * `RISCV_FORMAL_BUSLEN   - 1 : 0] rvfi_bus_rdata; \
  (* keep *) wire [`RISCV_FORMAL_NBUS * `RISCV_FORMAL_BUSLEN   - 1 : 0] rvfi_bus_wdata;
`define RVFI_BUS_OUTPUTS_NOSEP \
  output [`RISCV_FORMAL_NBUS                          - 1 : 0] rvfi_bus_valid, \
  output [`RISCV_FORMAL_NBUS                          - 1 : 0] rvfi_bus_insn , \
  output [`RISCV_FORMAL_NBUS                          - 1 : 0] rvfi_bus_data , \
  output [`RISCV_FORMAL_NBUS                          - 1 : 0] rvfi_bus_fault, \
  output [`RISCV_FORMAL_NBUS *   `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_bus_addr , \
  output [`RISCV_FORMAL_NBUS * `RISCV_FORMAL_BUSLEN/8 - 1 : 0] rvfi_bus_rmask, \
  output [`RISCV_FORMAL_NBUS * `RISCV_FORMAL_BUSLEN/8 - 1 : 0] rvfi_bus_wmask, \
  output [`RISCV_FORMAL_NBUS * `RISCV_FORMAL_BUSLEN   - 1 : 0] rvfi_bus_rdata, \
  output [`RISCV_FORMAL_NBUS * `RISCV_FORMAL_BUSLEN   - 1 : 0] rvfi_bus_wdata
`define RVFI_BUS_CHANNEL_OUTPUTS_NOSEP \
  output [                         0 : 0] rvfi_bus_valid, \
  output [                         0 : 0] rvfi_bus_insn , \
  output [                         0 : 0] rvfi_bus_data , \
  output [                         0 : 0] rvfi_bus_fault, \
  output [  `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_bus_addr , \
  output [`RISCV_FORMAL_BUSLEN/8 - 1 : 0] rvfi_bus_rmask, \
  output [`RISCV_FORMAL_BUSLEN/8 - 1 : 0] rvfi_bus_wmask, \
  output [`RISCV_FORMAL_BUSLEN   - 1 : 0] rvfi_bus_rdata, \
  output [`RISCV_FORMAL_BUSLEN   - 1 : 0] rvfi_bus_wdata
`define RVFI_BUS_INPUTS_NOSEP \
  input [`RISCV_FORMAL_NBUS                          - 1 : 0] rvfi_bus_valid, \
  input [`RISCV_FORMAL_NBUS                          - 1 : 0] rvfi_bus_insn , \
  input [`RISCV_FORMAL_NBUS                          - 1 : 0] rvfi_bus_data , \
  input [`RISCV_FORMAL_NBUS                          - 1 : 0] rvfi_bus_fault, \
  input [`RISCV_FORMAL_NBUS *   `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_bus_addr , \
  input [`RISCV_FORMAL_NBUS * `RISCV_FORMAL_BUSLEN/8 - 1 : 0] rvfi_bus_rmask, \
  input [`RISCV_FORMAL_NBUS * `RISCV_FORMAL_BUSLEN/8 - 1 : 0] rvfi_bus_wmask, \
  input [`RISCV_FORMAL_NBUS * `RISCV_FORMAL_BUSLEN   - 1 : 0] rvfi_bus_rdata, \
  input [`RISCV_FORMAL_NBUS * `RISCV_FORMAL_BUSLEN   - 1 : 0] rvfi_bus_wdata
`define RVFI_BUS_CHANNEL_INPUTS_NOSEP \
  input [                         0 : 0] rvfi_bus_valid, \
  input [                         0 : 0] rvfi_bus_insn , \
  input [                         0 : 0] rvfi_bus_data , \
  input [                         0 : 0] rvfi_bus_fault, \
  input [  `RISCV_FORMAL_XLEN   - 1 : 0] rvfi_bus_addr , \
  input [`RISCV_FORMAL_BUSLEN/8 - 1 : 0] rvfi_bus_rmask, \
  input [`RISCV_FORMAL_BUSLEN/8 - 1 : 0] rvfi_bus_wmask, \
  input [`RISCV_FORMAL_BUSLEN   - 1 : 0] rvfi_bus_rdata, \
  input [`RISCV_FORMAL_BUSLEN   - 1 : 0] rvfi_bus_wdata
`define RVFI_BUS_CONN_NOSEP \
  .rvfi_bus_valid (rvfi_bus_valid), \
  .rvfi_bus_insn  (rvfi_bus_insn ), \
  .rvfi_bus_data  (rvfi_bus_data ), \
  .rvfi_bus_fault (rvfi_bus_fault), \
  .rvfi_bus_addr  (rvfi_bus_addr ), \
  .rvfi_bus_rmask (rvfi_bus_rmask), \
  .rvfi_bus_wmask (rvfi_bus_wmask), \
  .rvfi_bus_rdata (rvfi_bus_rdata), \
  .rvfi_bus_wdata (rvfi_bus_wdata)
`define RVFI_BUS_CHANNEL_CONN_NOSEP(_idx) \
  .rvfi_bus_valid (rvfi_bus_valid [ _idx                           +:                    1  ]), \
  .rvfi_bus_insn  (rvfi_bus_insn  [ _idx                           +:                    1  ]), \
  .rvfi_bus_data  (rvfi_bus_data  [ _idx                           +:                    1  ]), \
  .rvfi_bus_fault (rvfi_bus_fault [ _idx                           +:                    1  ]), \
  .rvfi_bus_addr  (rvfi_bus_addr  [(_idx)*(  `RISCV_FORMAL_XLEN  ) +:   `RISCV_FORMAL_XLEN  ]), \
  .rvfi_bus_rmask (rvfi_bus_rmask [(_idx)*(`RISCV_FORMAL_BUSLEN/8) +: `RISCV_FORMAL_BUSLEN/8]), \
  .rvfi_bus_wmask (rvfi_bus_wmask [(_idx)*(`RISCV_FORMAL_BUSLEN/8) +: `RISCV_FORMAL_BUSLEN/8]), \
  .rvfi_bus_rdata (rvfi_bus_rdata [(_idx)*(`RISCV_FORMAL_BUSLEN  ) +: `RISCV_FORMAL_BUSLEN  ]), \
  .rvfi_bus_wdata (rvfi_bus_wdata [(_idx)*(`RISCV_FORMAL_BUSLEN  ) +: `RISCV_FORMAL_BUSLEN  ])
`define RVFI_BUS_GETCHANNEL(_idx) \
  wire [                         0 : 0] bus_valid = rvfi_bus_valid [ _idx                           +:                    1  ]; \
  wire [                         0 : 0] bus_insn  = rvfi_bus_insn  [ _idx                           +:                    1  ]; \
  wire [                         0 : 0] bus_data  = rvfi_bus_data  [ _idx                           +:                    1  ]; \
  wire [                         0 : 0] bus_fault = rvfi_bus_fault [ _idx                           +:                    1  ]; \
  wire [  `RISCV_FORMAL_XLEN   - 1 : 0] bus_addr  = rvfi_bus_addr  [(_idx)*(  `RISCV_FORMAL_XLEN  ) +:   `RISCV_FORMAL_XLEN  ]; \
  wire [`RISCV_FORMAL_BUSLEN/8 - 1 : 0] bus_rmask = rvfi_bus_rmask [(_idx)*(`RISCV_FORMAL_BUSLEN/8) +: `RISCV_FORMAL_BUSLEN/8]; \
  wire [`RISCV_FORMAL_BUSLEN/8 - 1 : 0] bus_wmask = rvfi_bus_wmask [(_idx)*(`RISCV_FORMAL_BUSLEN/8) +: `RISCV_FORMAL_BUSLEN/8]; \
  wire [`RISCV_FORMAL_BUSLEN   - 1 : 0] bus_rdata = rvfi_bus_rdata [(_idx)*(`RISCV_FORMAL_BUSLEN  ) +: `RISCV_FORMAL_BUSLEN  ]; \
  wire [`RISCV_FORMAL_BUSLEN   - 1 : 0] bus_wdata = rvfi_bus_wdata [(_idx)*(`RISCV_FORMAL_BUSLEN  ) +: `RISCV_FORMAL_BUSLEN  ];
`define RVFI_BUS_SIGNALS \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NBUS,                    1  , bus_valid) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NBUS,                    1  , bus_insn ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NBUS,                    1  , bus_data ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NBUS,                    1  , bus_fault) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NBUS,   `RISCV_FORMAL_XLEN  , bus_addr ) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NBUS, `RISCV_FORMAL_BUSLEN/8, bus_rmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NBUS, `RISCV_FORMAL_BUSLEN/8, bus_wmask) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NBUS, `RISCV_FORMAL_BUSLEN  , bus_rdata) \
  `RISCV_FORMAL_CHANNEL_SIGNAL(`RISCV_FORMAL_NBUS, `RISCV_FORMAL_BUSLEN  , bus_wdata)
`define RVFI_BUS_OUTPUTS , `RVFI_BUS_OUTPUTS_NOSEP
`define RVFI_BUS_INPUTS , `RVFI_BUS_INPUTS_NOSEP
`define RVFI_BUS_CONN  , `RVFI_BUS_CONN_NOSEP
`define RVFI_BUS_CHANNEL_OUTPUTS , `RVFI_BUS_CHANNEL_OUTPUTS_NOSEP
`define RVFI_BUS_CHANNEL_INPUTS , `RVFI_BUS_CHANNEL_INPUTS_NOSEP
`define RVFI_BUS_CHANNEL_CONN(_idx)  , `RVFI_BUS_CHANNEL_CONN_NOSEP(_idx)
`else
`define RVFI_BUS_WIRES
`define RVFI_BUS_OUTPUTS
`define RVFI_BUS_INPUTS
`define RVFI_BUS_CONN
`define RVFI_BUS_GETCHANNEL(_idx)
`endif

`define RVFI_BUS_CHANNEL(_name, _idx) \
generate if(1) begin:_name \
  `RVFI_BUS_GETCHANNEL(_idx) \
end endgenerate
