name: CI

on:
    push:
    pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    container: jurevreca12/iic-osic-tools-plus:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run RISCOF Tests
        run: |
          cd tb
          make riscof
