name: Run-RISCV-Arch-Tests

on:
  workflow_run:
    workflows: [Build-Docker-Image]
    types: [completed]
  pull_request:
  push:
    branches:
      - '**'

jobs:
  riscof:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: myimg
          path: ${{ runner.temp }}

      - name: Load Image
        run: |
          docker load --input ${{ runner.temp }}/iic-osic-tools-plus.tar
          docker image ls -a

