name: Run RISC-V Arch Tests using RISCOF Framework and Publish HTML Results

on:
  workflow_run:
    workflows: [docker-build]
    types:
     - completed

jobs:
  run-riscof-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: iic-osic-tools-plus
          path: ${{ runner.temp }}

      - name: Load Image
        run: |
          docker load --input ${{ runner.temp }}/iic-osic-tools-plus.tar
          docker image ls -a

