#.PHONY: all compile elaborate sim clean
# We use find to search for all verilog and system verilog files.
INC_DIR := ../../rtl/inc
JEDRO_1_DEFINES := $(INC_DIR)/jedro_1_defines.v
RTL_DIR := ../../rtl
TB_DIR := ..
TB_SUPPORT_DIR := ../support/.

RTL_FILES := $(shell find $(RTL_DIR) -name "*.v")



